import { StructuredTypeConfig } from 'angular-odata';

//#region ODataApi Imports
import { PatientEntity } from './patiententity.entity';
//#endregion

//#region ODataApi StrucutredTypeConfig
export const PatientEntityEntityConfig = {
    name: 'PatientEntity',
    annotations: [],
    fields: {
        Id: { type: 'Edm.Int32', key: true, ref: 'Id', nullable: false },
        Branchid: { type: 'Edm.Int32', nullable: false },
        Primkey: { type: 'Edm.String' },
        Patalpha: { type: 'Edm.String' },
        Socsec: { type: 'Edm.String' },
        Assignment: { type: 'Edm.Boolean', nullable: false },
        Firstname: { type: 'Edm.String' },
        Mi: { type: 'Edm.String' },
        Lastname: { type: 'Edm.String' },
        Suffix: { type: 'Edm.String' },
        Business: { type: 'Edm.String' },
        Terms: { type: 'Edm.String' },
        Sex: { type: 'Edm.String' },
        Address: { type: 'Edm.String' },
        Address2: { type: 'Edm.String' },
        City: { type: 'Edm.String' },
        State: { type: 'Edm.String' },
        Zip: { type: 'Edm.String' },
        Phone: { type: 'Edm.String' },
        Dob: { type: 'Edm.DateTimeOffset', nullable: false },
        Dod: { type: 'Edm.DateTimeOffset', nullable: false },
        Entrydate: { type: 'Edm.DateTimeOffset', nullable: false },
        Secondaryclaim: { type: 'Edm.String' },
        Groupno: { type: 'Edm.String' },
        Copaygroup: { type: 'Edm.String' },
        Referid: { type: 'Edm.Int32', nullable: false },
        Salesid: { type: 'Edm.Int32', nullable: false },
        Phykey: { type: 'Edm.String' },
        Physeq: { type: 'Edm.String' },
        Attnyid: { type: 'Edm.Int32', nullable: false },
        Diagnosis: { type: 'Edm.String' },
        Diagnosis2: { type: 'Edm.String' },
        Diagnosis3: { type: 'Edm.String' },
        Diagnosis4: { type: 'Edm.String' },
        Remarks: { type: 'Edm.String' },
        Billcycle: { type: 'Edm.String' },
        Arbalance: { type: 'Edm.Decimal', nullable: false },
        Lastpayment: { type: 'Edm.Decimal', nullable: false },
        Enteral: { type: 'Edm.Decimal', nullable: false },
        Injurydate: { type: 'Edm.DateTimeOffset', nullable: false },
        Lastpaymentdate: { type: 'Edm.DateTimeOffset', nullable: false },
        Memo: { type: 'Edm.String' },
        Workphone: { type: 'Edm.String' },
        Diagtext: { type: 'Edm.String' },
        Height: { type: 'Edm.String' },
        Weight: { type: 'Edm.String' },
        Litersperminute: { type: 'Edm.Decimal', nullable: false },
        Hoursperday: { type: 'Edm.Decimal', nullable: false },
        Lastdos: { type: 'Edm.DateTimeOffset', nullable: false },
        County: { type: 'Edm.String' },
        Emergencyname: { type: 'Edm.String' },
        Emergencyphone: { type: 'Edm.String' },
        Alternateid: { type: 'Edm.String' },
        Adduserid: { type: 'Edm.String' },
        Copay: { type: 'Edm.Decimal', nullable: false },
        Otherbill: { type: 'Edm.String' },
        Otherclaim: { type: 'Edm.String' },
        Othergroup: { type: 'Edm.String' },
        Operatorid: { type: 'Edm.String' },
        Arbalancemedicare: { type: 'Edm.Decimal', nullable: false },
        Arbalanceinsurance: { type: 'Edm.Decimal', nullable: false },
        Arbalancepatient: { type: 'Edm.Decimal', nullable: false },
        Primarybillto: { type: 'Edm.String' },
        Secondarybillto: { type: 'Edm.String' },
        Responsibleparty: { type: 'Edm.String' },
        Employer: { type: 'Edm.String' },
        Race: { type: 'Edm.String' },
        Ethnicity: { type: 'Edm.String' },
        Siteid: { type: 'Edm.String' },
        District: { type: 'Edm.String' },
        Datesent: { type: 'Edm.DateTimeOffset', nullable: false },
        Employmentrelatedaccident: { type: 'Edm.Boolean', nullable: false },
        Autoaccident: { type: 'Edm.Boolean', nullable: false },
        Otheraccident: { type: 'Edm.Boolean', nullable: false },
        Autoaccidentstate: { type: 'Edm.String' },
        Glucosetestsperday: { type: 'Edm.Decimal', nullable: false },
        Orderout: { type: 'Edm.DateTimeOffset', nullable: false },
        Orderin: { type: 'Edm.DateTimeOffset', nullable: false },
        Deductibleyear: { type: 'Edm.String' },
        Deductiblemet: { type: 'Edm.Boolean', nullable: false },
        Deductibleamount: { type: 'Edm.Decimal', nullable: false },
        Phykey2: { type: 'Edm.String' },
        Phykey3: { type: 'Edm.String' },
        Invoicemessage: { type: 'Edm.String' },
        Delete: { type: 'Edm.Boolean', nullable: false },
        Isinsulinpatient: { type: 'Edm.Boolean', nullable: false },
        Patientcategory: { type: 'Edm.String' },
        Recalldate: { type: 'Edm.DateTimeOffset', nullable: false },
        Maritalstatus: { type: 'Edm.String' },
        Email: { type: 'Edm.String' },
        Billingflashmessage: { type: 'Edm.String' },
        Cba: { type: 'Edm.String' },
        Refertodate: { type: 'Edm.DateTimeOffset', nullable: false },
        Pcpid: { type: 'Edm.Int32', nullable: false },
        Donotemail: { type: 'Edm.Boolean', nullable: false },
        Donotcall: { type: 'Edm.Boolean', nullable: false },
        Donotmailtext: { type: 'Edm.Boolean', nullable: false },
        Pwktypecode: { type: 'Edm.String' },
        Pwktransmissioncode: { type: 'Edm.String' },
        Pwkattachmentcn: { type: 'Edm.String' },
        Pwkccn: { type: 'Edm.String' },
        Route: { type: 'Edm.String' },
        Inventorylocation: { type: 'Edm.String' },
        Contactmethod: { type: 'Edm.String' },
        Cellphone: { type: 'Edm.String' },
        Language: { type: 'Edm.String' },
        Patientstatus: { type: 'Edm.String' },
        Besttime: { type: 'Edm.String' },
        Sendmail: { type: 'Edm.String' },
        Waistsize: { type: 'Edm.String' },
        Call: { type: 'Edm.String' },
        Sendemail: { type: 'Edm.String' },
        Sendtext: { type: 'Edm.String' },
        Discreetpackaging: { type: 'Edm.Boolean', nullable: false },
        Facilityid: { type: 'Edm.Int32', nullable: false },
        Medicarepatient: { type: 'Edm.String' },
        Pwocompleted: { type: 'Edm.String' },
        Chartnotes: { type: 'Edm.String' },
        Qualifiedcgm: { type: 'Edm.String' },
        Contactattempt1: { type: 'Edm.String' },
        Contactattempt2: { type: 'Edm.String' },
        Contactattempt3: { type: 'Edm.String' },
        Patientinterview: { type: 'Edm.String' },
        Insuranceverified: { type: 'Edm.String' },
        Completedpworeceived: { type: 'Edm.String' },
        Qualifyingnotesreceived: { type: 'Edm.String' },
        Dispositionholdnote: { type: 'Edm.String' },
        Referralcontact: { type: 'Edm.String' },
    },
} as StructuredTypeConfig<PatientEntity>;
//#endregion
