import { labelColorDefs } from 'app/shared/constants/aux-color-constants';

export const AppName = [
    {
        name: 'Abbott',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'AccessCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ARCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'AuditCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'AnalyticsCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'BillCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'BillTypeCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'BranchCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'CareManagementCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ChargeCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'CodeCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'CommCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ComplianceCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ConfigurationCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'Dexcom',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'EmployeeCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'EventTrackingCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'HotKeysCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'IcdCodeCenter',
        category: 'Centers',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'IdentityCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'InventoryCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'JobCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'LicenseCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'MapCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'OnboardingCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'PatientApp',
        category: 'Applications',
        type: 'public',
        icon: labelColorDefs['green'].text,
    },
    {
        name: 'PatientCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'PayorCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'PhysicianCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'PriceCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ProofOfDeliveryCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ReferralCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ReferralSourcePortal',
        category: 'Applications',
        type: 'public',
        icon: labelColorDefs['green'].text,
    },
    {
        name: 'ReorderCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ReportingCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'RetentionRateCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'SalesCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'SalesRepApp',
        category: 'Applications',
        type: 'private',
        icon: labelColorDefs['green'].text,
    },
    {
        name: 'ShortcutCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'TerritoryCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ValidationCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'VaultCenter',
        category: 'Centers',
        type: 'private',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'VendorCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'WorkOrderCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
    {
        name: 'ZipCodeCenter',
        category: 'Centers',
        type: 'public',
        icon: labelColorDefs['purple'].text,
    },
];
